# Generated by Django 4.2.5 on 2024-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_registermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='accountName',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='password',
            field=models.TextField(max_length=64),
        ),
    ]
